### PR TITLE
Update Otel deps and remove deprecated register_tracer

### LINKED ISSUE #3: OpenTelemetry.register_tracer/2 is undefined
This was removed in rc4: https://github.com/open-telemetry/opentelemetry-erlang/blob/f12732d2b6efa53330061f74b2a7dbd51e51abda/CHANGELOG.md#removed

I think the right change is just to remove this call. Please advise and I can make a PR.

### PR DESCRIPTION
**Pull request by fcarlislehg**
Fixes #3

### CODE REVIEW

**Comment by sax** [comment]
Awesome, thanks for the contribution! I'm just waiting to merge on having some time to test this change with one of our projects. Hopefully I can get that done either tonight or tomorrow morning.

**Comment by sax** [comment]
One problem I'm running into is that update the elixir deps requires jumping to a newer version of the `otel-collector` than we had been using, and updating the collector seems to require updating the `opentelemetry-js` libraries.

I'm in the middle of that morass, but it's taking a bit longer than I was hoping.

**Comment by fcarlislehg** [comment]
Oh! Fun!
That's what we get for using pre-releases right?!?!?!

Thanks for taking the time.

**Comment by sax** [comment]
If you wouldn't mind, could you take a look at these changes?

https://github.com/geometerio/geometrics/compare/e84bfe0ba45f4b1d298b30aa3c27c9e64c1c0a70...upgrade-opentelemetry

I have not tried deploying this to any of our applications yet, but they seem to work on my local computer. I'd be especially curious to know if you ran into any other issues that should be documented for others.

**Comment by fcarlislehg** [comment]
The changes and doc updates look good. I am not using JS traces currently so can't verify that, but I will update and test locally.

**Pull request merged**
